services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:8
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

  versitygw:
    image: versity/versitygw:latest
    command: posix /data
    environment:
      ROOT_ACCESS_KEY: ${S3_ACCESS_KEY}
      ROOT_SECRET_KEY: ${S3_SECRET_KEY}
    volumes:
      - ./data/versitygw:/data
    ports:
      - "9000:9000"

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI web dashboard

  mailpit:
    image: axllent/mailpit:1.30
    ports:
      - "1025:1025" # SMTP server port (point your app here)
      - "8025:8025" # Web UI Dashboard

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3 support
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
